resources:
  - name: yuval_repo
    type: GitRepo
    configuration:
      gitProvider: yuvalGithub
      path: mor2k1/linux
      branches:
        include: IntelliJ

  - name: docker_file
    type: Image
    configuration:
      registry: yuvalArtifactory
      sourceRepository: main-repohubvirt
      imageName: avigdor.jfrog.io/main-repohubvirt/ubuntu
      imageTag: latest
      autoPull: true

  - name: docker_build
    type: BuildInfo
    configuration:
      sourceArtifactory: yuvalArtifactory
      buildName: docker_build_yuval
      buildNumber: latest

  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: yuvalArtifactory
      buildName: Xray_Build
      buildNumber: ${run_numebr}

pipelines:
  - name: yuval_pipeline_build_docker
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: yuval_docker
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avigdor.jfrog.io/main-repohubvirt/ubuntu
          dockerImageTag: ${run_number}
          inputResources:
            - name: yuval_repo
            - name: docker_file
          integrations:
            - name: yuvalArtifactory
            
      - name: xray_scan
        type: XrayScan
        configuration:
          inputResources:
            - name: build_info
